const app = {};
app.a = 'Hello';
var str = 'aAAA';
var gTest = 'test'
var newVar = 'Aadwdaw'
var newVar2 = 'Aadwdaw'
var newVar3 = 'Aadwdaw'
var newVar5 = 'Aadwdaw'
var newVar4 = 'Aadwdaw'
var newVar6 = 'Aadwdaw'
var newVar7 = 'Aadwdaw'
var newVar8 = 'Aadwdaw'
